org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

# Mod properties
mod_id=zaharkuvalda
mod_name=Zahar Kuvalda
mod_version=1.0.0
mod_group_id=com.example.zaharkuvalda
mod_authors=Example
mod_description=Brush-grass and sledgehammer mod

# NeoForge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.172
neo_version_range=[21.1,)
loader_version_range=[1,)

# Mappings
mapping_channel=official
mapping_version=1.21.1
