modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
    modId="zaharkuvalda"
    version="1.0.0"
    displayName="Zahar Kuvalda"
    description="Brush-grass and sledgehammer mod"
    authors="Example"

[[dependencies.zaharkuvalda]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.zaharkuvalda]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"
